// admin-angular/src/app/pages/dashboard/dashboard.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="page-container">

      <h2 class="page-title">Dashboard</h2>

      <!-- Navigation Buttons -->
      <div class="quick-actions">
        <button (click)="goTo('home')">Home</button>
        <button (click)="goTo('pending')">Pending Tips</button>
        <button (click)="goTo('approved')">Approved Tips</button>
      </div>

      <!-- Dashboard Cards -->
      <div class="cards-container">
        <div class="card">
          <h3>Pending Tips</h3>
          <p>{{ pendingCount }}</p>
        </div>

        <div class="card">
          <h3>Approved Tips</h3>
          <p>{{ approvedCount }}</p>
        </div>
      </div>

    </div>
  `,
  styles: [`
    .page-container {
      max-width: 900px;
      margin: 0 auto;
      padding: 20px;
      text-align: center;
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      background-color: #bdd2ec;
    }

    .page-title {
      color: #010b15;
      margin-bottom: 25px;
      font-size: 28px;
      font-family: Geneva;
    }

    .quick-actions {
      margin-bottom: 30px;
      display: flex;
      gap: 15px;
      justify-content: center;
      flex-wrap: wrap;
    }

    .quick-actions button {
      padding: 10px 20px;
      border-radius: 8px;
      border: none;
      background-color: #2c7ace;
      color: white;
      cursor: pointer;
      transition: 0.2s;
      font-size: 14px;
    }

    .quick-actions button:hover {
      background-color: #00346b;
    }

    .cards-container {
      display: flex;
      flex-wrap: wrap;
      gap: 20px;
      justify-content: center;
    }

    .card {
      width: 250px;
      padding: 20px;
      border-radius: 10px;
      background-color: #9ac5f4;
      box-shadow: 0 4px 10px rgba(0,0,0,0.1);
      text-align: center;
    }

    .card h3 {
      margin-bottom: 10px;
      color: #333;
    }

    .card p {
      color: #555;
      font-size: 20px;
      font-weight: bold;
    }
  `]
})
export class DashboardComponent implements OnInit {

  pendingCount = 0;
  approvedCount = 0;

  // ✅ FIXED: Render backend URL
  backendUrl = "https://peerstudyhub-backend.onrender.com";

  constructor(private router: Router, private http: HttpClient) {}

  ngOnInit() {
    this.loadCounts();
  }

  goTo(page: string) {
    this.router.navigate([`/${page}`]);
  }

  loadCounts() {
    // Pending tips
    this.http.get<any[]>(`${this.backendUrl}/pending`)
      .subscribe(data => {
        this.pendingCount = data.filter(t => t !== null).length;
      }, err => console.error("Error loading pending tips:", err));

    // Approved tips
    this.http.get<any[]>(`${this.backendUrl}/approved`)
      .subscribe(data => {
        this.approvedCount = data.filter(t => t !== null).length;
      }, err => console.error("Error loading approved tips:", err));
  }

}

// student-react/src/pages/Dashboard.js
// import { useEffect, useState } from "react";

// function Dashboard() {
//   const [subjects, setSubjects] = useState([]);
//   const [view, setView] = useState("dashboard"); // dashboard / pending / approved
//   const [pendingTips, setPendingTips] = useState([]);
//   const [approvedTips, setApprovedTips] = useState([]);

//   // Fetch subjects
//   useEffect(() => {
//     fetch("http://localhost:5000/subjects")
//       .then(res => res.json())
//       .then(data => setSubjects(data))
//       .catch(err => console.log(err));
//   }, []);

//   // Fetch pending tips
//   useEffect(() => {
//     if (view === "pending") {
//       fetch("http://localhost:5000/pending")
//         .then(res => res.json())
//         .then(data => setPendingTips(data.filter(tip => tip !== null)))
//         .catch(err => console.log(err));
//     }
//   }, [view]);

//   // Fetch approved tips
//   useEffect(() => {
//     if (view === "approved") {
//       fetch("http://localhost:5000/approved")
//         .then(res => res.json())
//         .then(data => setApprovedTips(data.filter(tip => tip !== null)))
//         .catch(err => console.log(err));
//     }
//   }, [view]);

//   // --- Render ---
//   if (view === "pending") {
//     return (
//       <div style={styles.container}>
//         <h2 style={styles.title}>Pending Tips</h2>
//         <button onClick={() => setView("dashboard")} style={styles.backButton}>Back</button>

//         {pendingTips.length === 0 ? (
//           <p style={styles.emptyState}>No pending tips</p>
//         ) : (
//           <table style={styles.table}>
//             <thead>
//               <tr>
//                 <th>Topic</th>
//                 <th>Tip</th>
//               </tr>
//             </thead>
//             <tbody>
//               {pendingTips.map(tip => (
//                 <tr key={tip.id}>
//                   <td>{tip.topic}</td>
//                   <td>{tip.text}</td>
//                 </tr>
//               ))}
//             </tbody>
//           </table>
//         )}
//       </div>
//     );
//   }

//   if (view === "approved") {
//     return (
//       <div style={styles.container}>
//         <h2 style={styles.title}>Approved Tips</h2>
//         <button onClick={() => setView("dashboard")} style={styles.backButton}>Back</button>

//         {approvedTips.length === 0 ? (
//           <p style={styles.emptyState}>No approved tips</p>
//         ) : (
//           <table style={styles.table}>
//             <thead>
//               <tr>
//                 <th>Topic</th>
//                 <th>Tip</th>
//               </tr>
//             </thead>
//             <tbody>
//               {approvedTips.map(tip => (
//                 <tr key={tip.id}>
//                   <td>{tip.topic}</td>
//                   <td>{tip.text}</td>
//                 </tr>
//               ))}
//             </tbody>
//           </table>
//         )}
//       </div>
//     );
//   }

//   // Default dashboard view
//   return (
//     <div style={styles.container}>
//       <h2 style={styles.title}>Student Dashboard</h2>

//       <div style={styles.buttonGroup}>
//         <button onClick={() => setView("pending")} style={styles.button}>View Pending Tips</button>
//         <button onClick={() => setView("approved")} style={styles.button}>View Approved Tips</button>
//       </div>

//       {subjects.length === 0 ? (
//         <p style={styles.emptyState}>No subjects found</p>
//       ) : (
//         <div style={styles.subjectsContainer}>
//           {subjects.map(subject => (
//             <div key={subject.id} style={styles.subjectCard}>
//               <h3>{subject.subject}</h3>
//               <p>Semester: {subject.semester}</p>
//             </div>
//           ))}
//         </div>
//       )}
//     </div>
//   );
// }

// export default Dashboard;

// // --- Styles ---
// const styles = {
//   container: {
//     maxWidth: "900px",
//     margin: "40px auto",
//     padding: "20px",
//     fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
//     textAlign: "center",
   
//     borderRadius: "12px",
//     boxShadow: "0 6px 15px rgba(0,0,0,0.1)",
//     backgroundColor:"#9dc9f5"
//   },
//   title: {
//     color: "#020e1c",
//     marginBottom: "20px",
//     fontSize: "28px",
//      fontFamily:'Geneva'
//   },
//   buttonGroup: {
//     display: "flex",
//     justifyContent: "center",
//     gap: "20px",
//     marginBottom: "30px"
//   },
//   button: {
//     padding: "10px 20px",
//     borderRadius: "8px",
//     border: "none",
//     backgroundColor: "#0c3f76",
//     color: "white",
//     fontSize: "16px",
//     cursor: "pointer",
//   },
//   backButton: {
//     padding: "6px 12px",
//     borderRadius: "6px",
//     border: "none",
//     backgroundColor: "#6c757d",
//     color: "white",
//     fontSize: "14px",
//     cursor: "pointer",
//     marginBottom: "20px"
//   },
//   emptyState: {
//     color: "#666",
//     fontSize: "16px",
//     marginTop: "20px"
//   },
//   subjectsContainer: {
//     display: "flex",
//     flexWrap: "wrap",
//     gap: "20px",
//     justifyContent: "center"
//   },
//   subjectCard: {
//     width: "250px",
//     padding: "15px",
//     borderRadius: "10px",
//     background: "#ffffff",
//     boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
//     textAlign: "left",
//      backgroundColor: "#d7e5f5",
//   },
//   table: {
//     width: "100%",
//     borderCollapse: "collapse",
//     marginTop: "20px"
//   },
//   tableCell: {
//     border: "1px solid #891515",
//     padding: "8px",
//   }
// };
import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";

function Dashboard() {
  const [subjects, setSubjects] = useState([]);
  const [view, setView] = useState("dashboard");
  const navigate = useNavigate();
  const [pendingTips, setPendingTips] = useState([]);
  const [approvedTips, setApprovedTips] = useState([]);

  // Fetch subjects
  useEffect(() => {
    fetch("https://peerstudyhub-backend.onrender.com/subjects")
      .then(res => res.json())
      .then(data => setSubjects(data))
      .catch(err => console.log(err));
  }, []);

  // Fetch pending tips
  useEffect(() => {
    if (view === "pending") {
      fetch("https://peerstudyhub-backend.onrender.com/pending")
        .then(res => res.json())
        .then(data => setPendingTips(data.filter(tip => tip !== null)))
        .catch(err => console.log(err));
    }
  }, [view]);

  // Fetch approved tips
  useEffect(() => {
    if (view === "approved") {
      fetch("https://peerstudyhub-backend.onrender.com/approved")
        .then(res => res.json())
        .then(data => setApprovedTips(data.filter(tip => tip !== null)))
        .catch(err => console.log(err));
    }
  }, [view]);

  // Pending Tips View
  if (view === "pending") {
    return (
      <div style={styles.container}>
        <h2 style={styles.title}>Pending Tips</h2>
        <button
          onClick={() => setView("dashboard")}
          style={styles.backButton}
        >
          Back
        </button>

        {pendingTips.length === 0 ? (
          <p style={styles.emptyState}>No pending tips</p>
        ) : (
          <table style={styles.table}>
            <thead>
              <tr>
                <th>Topic</th>
                <th>Tip</th>
              </tr>
            </thead>
            <tbody>
              {pendingTips.map(tip => (
                <tr key={tip.id}>
                  <td>{tip.topic}</td>
                  <td>{tip.text}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    );
  }

  // Approved Tips View
  if (view === "approved") {
    return (
      <div style={styles.container}>
        <h2 style={styles.title}>Approved Tips</h2>
        <button
          onClick={() => setView("dashboard")}
          style={styles.backButton}
        >
          Back
        </button>

        {approvedTips.length === 0 ? (
          <p style={styles.emptyState}>No approved tips</p>
        ) : (
          <table style={styles.table}>
            <thead>
              <tr>
                <th>Topic</th>
                <th>Tip</th>
              </tr>
            </thead>
            <tbody>
              {approvedTips.map(tip => (
                <tr key={tip.id}>
                  <td>{tip.topic}</td>
                  <td>{tip.text}</td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    );
  }

  // Dashboard View
  return (
    <div style={styles.container}>
      <h2 style={styles.title}>Student Dashboard</h2>

      <div style={styles.buttonGroup}>
        <button
          onClick={() => setView("pending")}
          style={styles.button}
        >
          View Pending Tips
        </button>

        <button
          onClick={() => setView("approved")}
          style={styles.button}
        >
          View Approved Tips
        </button>

        <button
          onClick={() => navigate("/submit")}
          style={styles.button}
        >
          Submit Tip
        </button>
      </div>

      {subjects.length === 0 ? (
        <p style={styles.emptyState}>No subjects found</p>
      ) : (
        <div style={styles.subjectsContainer}>
          {subjects.map(subject => (
            <div key={subject.id} style={styles.subjectCard}>
              <h3>{subject.subject}</h3>
              <p>Semester: {subject.semester}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

export default Dashboard;

// --- Styles ---
const styles = {
  container: {
    maxWidth: "900px",
    margin: "40px auto",
    padding: "20px",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    textAlign: "center",
    borderRadius: "12px",
    boxShadow: "0 6px 15px rgba(0,0,0,0.1)",
    backgroundColor: "#9dc9f5",
  },

  title: {
    color: "#020e1c",
    marginBottom: "20px",
    fontSize: "28px",
    fontFamily: "Geneva",
  },

  buttonGroup: {
    display: "flex",
    justifyContent: "center",
    gap: "20px",
    marginBottom: "30px",
  },

  button: {
    padding: "10px 20px",
    borderRadius: "8px",
    border: "none",
    backgroundColor: "#0c3f76",
    color: "white",
    fontSize: "16px",
    cursor: "pointer",
  },

  backButton: {
    padding: "6px 12px",
    borderRadius: "6px",
    border: "none",
    backgroundColor: "#6c757d",
    color: "white",
    fontSize: "14px",
    cursor: "pointer",
    marginBottom: "20px",
  },

  emptyState: {
    color: "#666",
    fontSize: "16px",
    marginTop: "20px",
  },

  subjectsContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "20px",
    justifyContent: "center",
  },

  subjectCard: {
    width: "250px",
    padding: "15px",
    borderRadius: "10px",
    background: "#d7e5f5",
    boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
    textAlign: "left",
  },

  table: {
    width: "100%",
    borderCollapse: "collapse",
    marginTop: "20px",
  },

  tableCell: {
    border: "1px solid #891515",
    padding: "8px",
  },
};
