// student-react/src/pages/ApprovedTips.js
// import { useEffect, useState } from "react";

// function ApprovedTips() {
//   const [tips, setTips] = useState([]);

//   useEffect(() => {
//     fetch("http://localhost:5000/approved")
//       .then(res => res.json())
//       .then(data => setTips(data.filter(tip => tip !== null))); // remove nulls
//   }, []);

//   return (
//     <div style={styles.pageContainer}>
//       <h2 style={styles.pageTitle}>Approved Tips</h2>

//       {tips.length === 0 && (
//         <p style={styles.emptyState}>No approved tips yet</p>
//       )}

//       <div style={styles.cardsContainer}>
//         {tips.map(tip => (
//           <div key={tip.id} style={styles.card}>
//             <h3 style={styles.cardTitle}>{tip.topic}</h3>
//             <p style={styles.cardText}>{tip.text}</p>
//           </div>
//         ))}
//       </div>
//     </div>
//   );
// }

// export default ApprovedTips;

// // ---- Styles ----
// const styles = {
//   pageContainer: {
//     maxWidth: "900px",
//     margin: "0 auto",
//     padding: "20px",
//     fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
//     textAlign: "center",
//   },
//   pageTitle: {
//     color: "#007bff",
//     marginBottom: "25px",
//     fontSize: "28px",
//   },
//   emptyState: {
//     color: "#666",
//     fontSize: "18px",
//     marginTop: "40px",
//   },
//   cardsContainer: {
//     display: "flex",
//     flexWrap: "wrap",
//     gap: "20px",
//     justifyContent: "center",
//     maxHeight: "70vh",
//     overflowY: "auto",
//     paddingBottom: "10px",
//   },
//   card: {
//     width: "280px",
//     padding: "15px",
//     borderRadius: "10px",
//     background: "#f8f9fa",
//     boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
//     textAlign: "left",
//     flexShrink: 0,
//   },
//   cardTitle: {
//     marginBottom: "10px",
//     color: "#333",
//   },
//   cardText: {
//     color: "#555",
//     fontSize: "14px",
//   },
// };
import { useEffect, useState } from "react";

function ApprovedTips() {
  const [tips, setTips] = useState([]);

  useEffect(() => {
    fetch("https://peerstudyhub-backend.onrender.com/approved")
      .then(res => res.json())
      .then(data => setTips(data.filter(tip => tip !== null)))
      .catch(err => console.error("Error fetching approved tips:", err));
  }, []);

  return (
    <div style={styles.pageContainer}>
      <h2 style={styles.pageTitle}>Approved Tips</h2>

      {tips.length === 0 && (
        <p style={styles.emptyState}>No approved tips yet</p>
      )}

      <div style={styles.cardsContainer}>
        {tips.map(tip => (
          <div key={tip.id} style={styles.card}>
            <h3 style={styles.cardTitle}>{tip.topic}</h3>
            <p style={styles.cardText}>{tip.text}</p>
          </div>
        ))}
      </div>
    </div>
  );
}

export default ApprovedTips;

// ---- Styles ----
const styles = {
  pageContainer: {
    maxWidth: "900px",
    margin: "0 auto",
    padding: "20px",
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    textAlign: "center",
  },
  pageTitle: {
    color: "#007bff",
    marginBottom: "25px",
    fontSize: "28px",
  },
  emptyState: {
    color: "#666",
    fontSize: "18px",
    marginTop: "40px",
  },
  cardsContainer: {
    display: "flex",
    flexWrap: "wrap",
    gap: "20px",
    justifyContent: "center",
    maxHeight: "70vh",
    overflowY: "auto",
    paddingBottom: "10px",
  },
  card: {
    width: "280px",
    padding: "15px",
    borderRadius: "10px",
    background: "#f8f9fa",
    boxShadow: "0 4px 10px rgba(0,0,0,0.1)",
    textAlign: "left",
    flexShrink: 0,
  },
  cardTitle: {
    marginBottom: "10px",
    color: "#333",
  },
  cardText: {
    color: "#555",
    fontSize: "14px",
  },
};

// admin-angular/src/app/pages/approved-tips/approved-tips.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-approved-tips',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="page-container">

      <h2 class="page-title">{{ title }}</h2>

      <div *ngIf="tips.length === 0" class="empty-state">
        No {{ title.toLowerCase() }} yet
      </div>

      <div class="cards-container">
        <div *ngFor="let tip of tips" class="card">
          <h3>{{ tip.topic }}</h3>
          <p>{{ tip.text }}</p>

          <div *ngIf="tip.studentId || tip.date" class="card-footer">
            <span *ngIf="tip.studentId">Student: {{ tip.studentId }}</span>
            <span *ngIf="tip.date"> | Date: {{ tip.date }}</span>
          </div>
        </div>
      </div>

    </div>
  `,
  styles: [`
    .page-container {
      padding: 20px;
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      text-align: center;
      background-color: #052d58;
    }

    .page-title {
      margin-bottom: 25px;
      color: #efe7e7;
      font-family: Geneva;
      font-size: 28px;
    }

    .empty-state {
      color: #140101;
      font-size: 18px;
      margin-top: 40px;
    }

    .cards-container {
      display: flex;
      flex-wrap: wrap;
      gap: 20px;
      justify-content: center;
      max-height: 75vh;
      overflow-y: auto;
      padding-bottom: 10px;
    }

    .card {
      width: 300px;
      padding: 15px;
      border-radius: 10px;
      background-color: #c6e2fb;
      box-shadow: 0 4px 12px rgba(0,0,0,0.1);
      flex-shrink: 0;
      text-align: left;
    }

    .card h3 {
      margin-bottom: 8px;
      color: #100000;
    }

    .card p {
      color: #1a0000;
      font-size: 14px;
    }

    .card-footer {
      margin-top: 10px;
      font-size: 12px;
      color: #0c0101;
    }
  `]
})
export class ApprovedTipsComponent implements OnInit {

  title = "Approved Tips";
  tips: any[] = [];

  // ✅ FIXED: Render backend URL
  private backendUrl = "https://peerstudyhub-backend.onrender.com";

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.http.get<any[]>(`${this.backendUrl}/approved`)
      .subscribe(
        data => {
          this.tips = data.filter(tip => tip !== null);
          console.log("APPROVED:", this.tips);
        },
        err => console.error("Failed to load approved tips", err)
      );
  }
}
